import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { CartProvider } from "@/providers/cart-provider";
import { Container } from "@/components/ui/container";
import { CategoriesNavbar } from "@/components/categories-navbar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Container>
      <CartProvider>
        {children}
      </CartProvider>
    </Container>
  );
}
